In [1]:
import numpy as np
marks = np.array([78, 65, 89, 56, 92])
print("Marks:", marks)
print("Number of dimensions:", marks.ndim)
print("Shape:", marks.shape)
print("Size:", marks.size)
print("Data type:", marks.dtype)

Marks: [78 65 89 56 92]
Number of dimensions: 1
Shape: (5,)
Size: 5
Data type: int64


In [2]:
import numpy as np
marks = np.array([72, 85, 64, 90, 76])
print("Marks:", marks)
print("First student:", marks[0])
print("Third student:", marks[2])
print("Last student:", marks[-1])

print("First three students:", marks[:3])
print("Second to fourth students:", marks[1:4])

Marks: [72 85 64 90 76]
First student: 72
Third student: 64
Last student: 76
First three students: [72 85 64]
Second to fourth students: [85 64 90]


In [3]:
import numpy as np
marks = np.array([
    78, 85, 90,
    65, 72, 80,
    88, 91, 84,
    56, 62, 70,
    95, 89, 92
])
marks = marks.reshape(5, 3)

print("Subject-wise marks:")
print(marks)

Subject-wise marks:
[[78 85 90]
 [65 72 80]
 [88 91 84]
 [56 62 70]
 [95 89 92]]


In [4]:
import numpy as np

internal = np.array([20, 18, 19, 17, 16])
external = np.array([65, 70, 68, 72, 75])
final_marks = internal + external
print("Internal marks:", internal)
print("External marks:", external)
print("Final marks:", final_marks)

Internal marks: [20 18 19 17 16]
External marks: [65 70 68 72 75]
Final marks: [85 88 87 89 91]


In [5]:
import numpy as np
marks = np.array([45, 78, 56, 32, 91])
passed = marks >= 50
print("Marks:", marks)
print("Students scoring 50 or above:", marks[passed])
print("Pass/Fail status:", passed)

Marks: [45 78 56 32 91]
Students scoring 50 or above: [78 56 91]
Pass/Fail status: [False  True  True False  True]


In [6]:
import numpy as np
marks = np.array([
    [78, 85, 90],
    [65, 72, 80],
    [88, 91, 84],
    [56, 62, 70],
    [95, 89, 92]
])
average = np.mean(marks, axis=1)
print("Marks:")
print(marks)
print("Average marks of each student:")
print(average)

Marks:
[[78 85 90]
 [65 72 80]
 [88 91 84]
 [56 62 70]
 [95 89 92]]
Average marks of each student:
[84.33333333 72.33333333 87.66666667 62.66666667 92.        ]


In [7]:
import numpy as np
marks = np.array([67, 82, 91, 74, 58])
print("Marks:", marks)
print("Total:", np.sum(marks))
print("Average:", np.mean(marks))
print("Highest:", np.max(marks))
print("Lowest:", np.min(marks))
print("Standard deviation:", np.std(marks))

Marks: [67 82 91 74 58]
Total: 372
Average: 74.4
Highest: 91
Lowest: 58
Standard deviation: 11.46472851837321


In [8]:
import numpy as np
marks = np.array([
    [78, 85, 90],
    [65, 72, 80],
    [88, 91, 84],
    [56, 62, 70],
    [95, 89, 92]
])

subject_total = np.sum(marks, axis=0)
print("Marks:")
print(marks)
print("Total marks in each subject:")
print(subject_total)

Marks:
[[78 85 90]
 [65 72 80]
 [88 91 84]
 [56 62 70]
 [95 89 92]]
Total marks in each subject:
[382 399 416]


In [9]:
import numpy as np
marks = np.array([
    [78, 85, 90],
    [65, 72, 80],
    [88, 91, 84],
    [56, 62, 70],
    [95, 89, 92]
])

student_total = np.sum(marks, axis=1)
print("Marks:")
print(marks)
print("Total marks of each student:")
print(student_total)

Marks:
[[78 85 90]
 [65 72 80]
 [88 91 84]
 [56 62 70]
 [95 89 92]]
Total marks of each student:
[253 217 263 188 276]


In [10]:
import numpy as np
marks = np.array([245, 278, 219, 290, 256])
sorted_marks = np.sort(marks)[::-1]
ranking = np.argsort(marks)[::-1]
print("Original marks:", marks)
print("Marks in descending order:", sorted_marks)

print("Student ranking:")
for rank, student in enumerate(ranking, start=1):
    print("Rank", rank, "- Student", student + 1,
          "- Marks:", marks[student])

Original marks: [245 278 219 290 256]
Marks in descending order: [290 278 256 245 219]
Student ranking:
Rank 1 - Student 4 - Marks: 290
Rank 2 - Student 2 - Marks: 278
Rank 3 - Student 5 - Marks: 256
Rank 4 - Student 1 - Marks: 245
Rank 5 - Student 3 - Marks: 219


In [11]:
import numpy as np
marks = np.array([85, 92, 85, 76, 92])
unique_marks = np.unique(marks)
print("Marks:", marks)
print("Unique marks:", unique_marks)

Marks: [85 92 85 76 92]
Unique marks: [76 85 92]


In [12]:
import numpy as np
marks = np.array([78, 85, np.nan, 92, 67])
average = np.nanmean(marks)
print("Marks:", marks)
print("Average without considering missing value:", average)

Marks: [78. 85. nan 92. 67.]
Average without considering missing value: 80.5


In [13]:
import numpy as np
marks = np.array([95, 82, 74, 61, 45])
grades = np.select(
    [
        marks >= 90,
        marks >= 80,
        marks >= 70,
        marks >= 60,
        marks >= 50
    ],
    [
        "A+",
        "A",
        "B",
        "C",
        "D"
    ],
    default="F"
)
print("Marks:", marks)
print("Grades:", grades)

Marks: [95 82 74 61 45]
Grades: ['A+' 'A' 'B' 'C' 'F']


In [14]:
import numpy as np
marks = np.random.randint(0, 101, size=5)
print("Randomly generated marks:", marks)
print("Total:", np.sum(marks))
print("Average:", np.mean(marks))
print("Highest:", np.max(marks))
print("Lowest:", np.min(marks))
print("Standard deviation:", np.std(marks))

Randomly generated marks: [70 73 36 53 83]
Total: 315
Average: 63.0
Highest: 83
Lowest: 36
Standard deviation: 16.601204775557708


In [15]:
import numpy as np
marks = np.array([
    [78, 85, 90],
    [65, 72, 80],
    [88, 91, 84],
    [56, 62, 70],
    [95, 89, 92]
])

total = np.sum(marks, axis=1)
average = np.mean(marks, axis=1)
highest = np.max(marks, axis=1)
lowest = np.min(marks, axis=1)
class_average = np.mean(total)
above_average = np.where(total > class_average)[0]

print("Marks:")
print(marks)
print("\nTotal marks:", total)
print("Average marks:", average)
print("Highest marks:", highest)
print("Lowest marks:", lowest)
print("Class average total:", class_average)
print("Students performing above class average:")
for student in above_average:
    print("Student", student + 1, "- Total:", total[student])

Marks:
[[78 85 90]
 [65 72 80]
 [88 91 84]
 [56 62 70]
 [95 89 92]]

Total marks: [253 217 263 188 276]
Average marks: [84.33333333 72.33333333 87.66666667 62.66666667 92.        ]
Highest marks: [90 80 91 70 95]
Lowest marks: [78 65 84 56 89]
Class average total: 239.4
Students performing above class average:
Student 1 - Total: 253
Student 3 - Total: 263
Student 5 - Total: 276


In [16]:
start = int(input("Enter starting number: "))
end = int(input("Enter ending number: "))
print("Prime numbers:")
for num in range(start, end + 1):
    if num < 2:
        continue

    is_prime = True
    for i in range(2, int(num ** 0.5) + 1):
        if num % i == 0:
            is_prime = False
            break

    if is_prime:
        print(num, end=" ")

Enter starting number: 10
Enter ending number: 20
Prime numbers:
11 13 17 19 

In [17]:
def factorial(n):
    if n == 0 or n == 1:
        return 1
    return n * factorial(n - 1)
n = int(input("Enter a number: "))
print("Factorial:", factorial(n))

Enter a number: 15
Factorial: 1307674368000


In [18]:
numbers = [1, 2, 3, 4, 5]
squares = list(map(lambda x: x * x, numbers))
print("Numbers:", numbers)
print("Squares:", squares)

Numbers: [1, 2, 3, 4, 5]
Squares: [1, 4, 9, 16, 25]


In [19]:
numbers = [10, 25, 7, 45, 32, 45, 18]
unique_numbers = list(set(numbers))
unique_numbers.sort()
print("List:", numbers)
print("Second largest:", unique_numbers[-2])

List: [10, 25, 7, 45, 32, 45, 18]
Second largest: 32


In [20]:
text = input("Enter a string: ")
frequency = {}
for char in text:
    if char in frequency:
        frequency[char] += 1
    else:
        frequency[char] = 1
print("Character frequency:")
for char, count in frequency.items():
    print(char, ":", count)

Enter a string: darshani
Character frequency:
d : 1
a : 2
r : 1
s : 1
h : 1
n : 1
i : 1


In [21]:
import math

radius = float(input("Enter radius: "))

area = math.pi * radius * radius

print("Radius:", radius)
print("Area of circle:", area)

Enter radius: 5
Radius: 5.0
Area of circle: 78.53981633974483


In [22]:
text = input("Enter a string: ")
reversed_string = ""
for char in text:
    reversed_string = char + reversed_string
print("Original string:", text)
print("Reversed string:", reversed_string)

Enter a string: darshani
Original string: darshani
Reversed string: inahsrad


In [23]:
numbers = [10, 20, 10, 30, 20, 40, 30]
unique = []
for num in numbers:
    if num not in unique:
        unique.append(num)
print("Original list:", numbers)
print("List after removing duplicates:", unique)

Original list: [10, 20, 10, 30, 20, 40, 30]
List after removing duplicates: [10, 20, 30, 40]


In [25]:
dict1 = {"name": "Darshani", "age": 20}
dict2 = {"department": "CSE", "year": 3}
merged = dict1.copy()
merged.update(dict2)
print("Dictionary 1:", dict1)
print("Dictionary 2:", dict2)
print("Merged dictionary:", merged)

Dictionary 1: {'name': 'Darshani', 'age': 20}
Dictionary 2: {'department': 'CSE', 'year': 3}
Merged dictionary: {'name': 'Darshani', 'age': 20, 'department': 'CSE', 'year': 3}


In [27]:
def fibonacci(n):
    if n <= 1:
        return n
    return fibonacci(n - 1) + fibonacci(n - 2)
n = int(input("Enter number of terms: "))
print("Fibonacci series:")
for i in range(n):
    print(fibonacci(i), end=" ")

Enter number of terms: 5
Fibonacci series:
0 1 1 2 3 

In [28]:
def calculate(a, b, operation):
    if operation == "+":
        return a + b
    elif operation == "-":
        return a - b
    elif operation == "*":
        return a * b
    elif operation == "/":
        if b == 0:
            return "Cannot divide by zero"
        return a / b
    else:
        return "Invalid operation"
a = float(input("Enter first number: "))
b = float(input("Enter second number: "))
operation = input("Enter operation (+, -, *, /): ")
result = calculate(a, b, operation)
print("Result:", result)

Enter first number: 20
Enter second number: 60
Enter operation (+, -, *, /): *
Result: 1200.0


In [29]:
def sum_numbers(*args):
    total = 0
    for num in args:
        total += num
    return total
print("Sum:", sum_numbers(10, 20, 30, 40))

Sum: 100


In [30]:
def employee(**args):
    print("Employee Information")
    for key, value in args.items():
        print(key, ":", value)
employee(
    name="Darshani",
    ID=101,
    department="CSE",
    salary=50000
)

Employee Information
name : Darshani
ID : 101
department : CSE
salary : 50000


In [31]:
def remove_duplicates(lst):
    unique = []
    for item in lst:
        if item not in unique:
            unique.append(item)
    return unique
numbers = [10, 20, 10, 30, 20, 40, 30]
print("Original list:", numbers)
print("Unique list:", remove_duplicates(numbers))

Original list: [10, 20, 10, 30, 20, 40, 30]
Unique list: [10, 20, 30, 40]


In [32]:
numbers = [(1, 5), (2, 3), (4, 1)]
sorted_numbers = sorted(numbers, key=lambda x: x[1])
print("Original list:", numbers)
print("Sorted list:", sorted_numbers)

Original list: [(1, 5), (2, 3), (4, 1)]
Sorted list: [(4, 1), (2, 3), (1, 5)]
